development:
  adapter: mysql2
  encoding: utf8
  database: next_market_dev
  username: next
  password: next
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: next_market_test
  username: next
  password: next
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: next_market
  username: next
  password: next
  host: localhost
  port: 3306
